### ISSUE TITLE
Adds-on can't be installed because of incompatible HW (Raspberry PI 4)

### ISSUE THREAD

**Issue by acenuke** [lichr/zircon-ha-proxy#8]
When trying to install the add-on, I get this error:
This add-on is not compatible with the processor of your device or the operating system you have installed on your device.

![image](https://github.com/lichr/zircon-ha-proxy/assets/10014367/e9fdd02d-5fa7-4098-859b-965f00ad52f6)

My HW is a Raspberry Pi 4 (rpi4-64) with 8GB Ram and HAOS 11.5 (latest)

**Comment by chris-xinhai-li** [comment]
Thank you for reporting the issue. Our first beta release currently only supports AMD64 CPUs. We plan to add support for the Raspberry Pi 4 in our next beta release.
